pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    curl https://nixos.org/nix/install | sh
  displayName: 'Install deps'
- script: |
    . /home/vsts/.nix-profile/etc/profile.d/nix.sh
    nix-shell --run make
  displayName: 'Make'

